name: After github template is used

# Thanks to: https://github.com/actions/toolkit/issues/1054#issuecomment-1142634600

on:
  # This event triggers on initial creation of new repo from github template
  push:
    branches:
      - '**'

jobs:
  remove-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Remove files
      run: |
        rm readme.md
        rm -r .github/
        rm degit.json
        echo "> [Template Used](https://github.com/metruzanca/ga-vercel-demo)" >> readme.md
      shell: bash

    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Cleaned up the template for you! <3"
